apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webserver
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/michaelkotelnikov/rhacm-workshop.git
      revision: master
      directories:
      - path: 04.Application-Lifecycle/exercise-argocd/application-resources/values/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: demo-project-argocd
      source:
        repoURL: https://github.com/michaelkotelnikov/rhacm-workshop.git
        targetRevision: master
        path: 04.Application-Lifecycle/exercise-argocd/application-resources/
        helm:
          valueFiles:
          - 'values/{{path.basename}}/values.yaml'
      destination:
        name: 'local-cluster'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
