---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: mariadb-app
  namespace: mariadb
spec:
  type: Git
  pathname: https://github.com/michaelkotelnikov/rhacm-workshop.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: prod-clusters
  namespace: mariadb
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      environment: production
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mariadb-app
  namespace: mariadb
  labels:
    app: mariadb-app
  annotations:
    apps.open-cluster-management.io/github-path: 07.Ansible-Tower-Integration/demo-application/mariadb-resources
    apps.open-cluster-management.io/git-branch: master
spec:
  channel: mariadb/mariadb-app
  placement:
    placementRef:
      kind: PlacementRule
      name: prod-clusters
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: mariadb-app
  namespace: mariadb
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - mariadb-app
